language: c
dist: bionic

notifications:
  email: false

before_install:
  sudo apt-get install -y libsqlite3-dev cppcheck valgrind gcc-4.8

env:
  - VALGRIND=1 ARCH=64 DEVELOPER=0 COMPILER=gcc TEST_GROUP=3 TEST_GROUP_COUNT=3 SOURCE_CHECK_ONLY=false
  - VALGRIND=1 ARCH=64 DEVELOPER=1 COMPILER=gcc TEST_GROUP=6 TEST_GROUP_COUNT=6 SOURCE_CHECK_ONLY=false
cache:
  directories:
    - dependencies
    - external

script:
  .travis/build.sh
